# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: 打包项目

on:
  push:
  #branches: [ main ]
  #pull_request:
  #branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3 # v3.1.0

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: Plugins
          path: build/libs/*.jar

      # create release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          draft: true
          fail_on_unmatched_files: true